name: Build and Test the project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Install pre-req packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python-is-python3

      # - name: Build the code
      #   run: |
      #     make

      - name: Compile the code
        run: |
          gcc -Wall -Wextra -g test.c rijndael.c -o test

      - name: Run C tests
        run: |
          ./test

      - name: Run Final unit test
        run: |
          pip install "git+https://github.com/boppreh/aes.git‚Äù
          python3 ./AssignmentTest.py
